version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  api:
    build: .
    environment:
      DATABASE_URL: postgres://app:app@db:5432/app?sslmode=disable
      JWT_SECRET: dev-secret
      CORS_ORIGINS: "*"
      PORT: "4000"
    depends_on:
      - db
    ports:
      - "4000:4000"


